### ISSUE TITLE
npm 安装报错

### ISSUE THREAD

**Issue by dsky1990** [seeleteam/SeeleWallet#46]
![image](https://user-images.githubusercontent.com/1579516/55382285-e096b680-5557-11e9-83e2-c6f07402a39a.png)

**Comment by LincolnZeng** [comment]
Please use English:

for this Issue, in your /path/to/SeeleWallet/, 
please try:

1. rm -rf node_modules
2. rm -rf package-lock.json
3. npm install
4. npm add electron-rebuild
5. ./node_modules/.bin/electron-rebuild
6. npm start
