### ISSUE TITLE
Accounts Overview Screen

### ISSUE THREAD

**Issue by troytrojan01** [seeleteam/SeeleWallet#49]
Once you select an account in the "Accounts Overview" screen there is no way to get back to the "Accounts Overview" screen to select a different account. The only way is to restart the wallet. There needs to be a back button or a home button to get back to the "Accounts Overview" screen.

**Comment by LincolnZeng** [comment]
Just click "WALLET" tab.

**Comment by troytrojan01** [comment]
The wallet tab takes you back to the individual wallet you click on the "Accounts Overview" screen. There's no way to get back to the other accounts. see attached.
![wallet tab-screen](https://user-images.githubusercontent.com/39805603/55673243-f4e5f680-586a-11e9-9b0e-1dc216d3859b.GIF)

**Comment by dsky1990** [comment]
@troytrojan01  how to build wallet?

**Comment by troytrojan01** [comment]
They had the .exe on here but it looks like it's been removed. That's how installed it.

**Comment by dsky1990** [comment]
@troytrojan01  yes, the package all removed

**Comment by troytrojan01** [comment]
We can close this one...I found out you have to click the account name and then it will return to the overview screen.
