### ISSUE TITLE
Seele-wallet import keyfile error

### ISSUE THREAD

**Issue by troytrojan01** [seeleteam/SeeleWallet#50]
When importing a keyfile. I get "the account is invalid for: hex string without 0x prefix" even though it does have the prefix. It imports the file fine, but the constant pop-up is annoying.
![seele-import-error](https://user-images.githubusercontent.com/39805603/55670824-86933b00-584e-11e9-9d87-04790970fb67.GIF)

**Comment by LincolnZeng** [comment]
Please make sure you keyfile name is your publickey

**Comment by troytrojan01** [comment]
I did use a public key and the import does work....my only issue is with the pop-up. it seems like since my imports are succesful there shouldn't be a pop-up error.

**Comment by troytrojan01** [comment]
We can close this. when i imported keys into a new wallet that i exported from the wallet, i didn't get the pop-up.
