### ISSUE TITLE
Seele Wallet - Beta - Windows - freeze when trying to sent funds

### ISSUE THREAD

**Issue by Bambarello** [seeleteam/SeeleWallet#68]
The wallet (windows beta release) is freezing when trying to send funds from one address to another (within 1 shard as well as cross-shard).

1) firewall opened
2) wallet in sync
3) network status shows connected nodes as green and in sync up to date
4) when trying to "send" -> wallet freezes after pressing button "send"

**Comment by muyiy** [comment]
Try opening developer options and see if there is any helpful error messages.

**Comment by Bambarello** [comment]
Why you closed the issue, it was not closed or resolved.

**Comment by Bambarello** [comment]
Here are some logs:

After pressing "send" button"

`F:\Wallets\SeeleWall….js\src\seele.js:44 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by muyiy** [comment]
Please provide a screenshot of all the logs, including non-errors.

**Comment by Bambarello** [comment]
Here are screens and steps
[Seele wallet issue.docx](https://github.com/seeleteam/SeeleWallet/files/3746558/Seele.wallet.issue.docx)

**Comment by muyiy** [comment]
The newer release has more log outputs, try viewing the logs again.
