### ISSUE TITLE
invalid key file could not decrypt key with given passphrase

### ISSUE THREAD

**Issue by aidanni** [seeleteam/SeeleWallet#72]
转账时出现
invalid key file could not decrypt key with given passphrase这个提示  密码都是正确的

**Comment by aidanni** [comment]
{
	"version": 1,
	"address": "",
	"crypto": {
		"ciphertext": "",
		"iv": "",
		"salt": "",
		"mac": ""
	}
}

能详细介绍一下导出账号里这些参数么？挖矿创建的账号只有账号和私匙，这些都该填什么？

**Comment by muyiy** [comment]
Does your keyfile name contain spaces?

**Comment by aidanni** [comment]
> Does your keyfile name contain spaces?

no spaces

**Comment by muyiy** [comment]
can you open your keyfile with client?

**Comment by aidanni** [comment]
> can you open your keyfile with client?

yes, but mining only has Public key and private key,

{
"version": 1,
"address": "",  this is Public key 
"crypto": {
"ciphertext": "",
"iv": "",
"salt": "",
"mac": "" this is private key 
}
}
What else should I fill in

**Comment by muyiy** [comment]
you're not supposed to fill in your keyfile, they're meant to be generated from client and wallet.
