### ISSUE TITLE
Seele Wallet - Beta - Mac OSX. Can not click "Transact" or "More Options"

### ISSUE THREAD

**Issue by EndisNi9h** [seeleteam/SeeleWallet#73]
I have downloaded the Mac OSX Seele wallet and installed. I have also transferred some Seele Main Coins to test if it was working properly. The deposit was fine and showing in my wallet. The issue is that I can not click on "transact" or "more options". When I click, nothing happens. "View receipt" and "Call Contract" work, but nothing else. This is worrisome as I set up the wallet on Shard 1 rather than set up a private key. I am worried that I can not access these coins now. Please advise. Thank you kindly

**Comment by muyiy** [comment]
Known possibilities is a duplicated keyfile or a keyfile with spaces in its name

**Comment by EndisNi9h** [comment]
Creating a new keyfile without a space in its name worked. So I went into the Seele Wallet account file and changed the name of the original wallet so that there is no longer a space. That wallet now currently works as well. Thank you very much for your help and continued support and work
